"""update schema

Revision ID: 660038cda0df
Revises: 88b53816f07e
Create Date: 2026-05-12 10:59:13.150139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660038cda0df'
down_revision: Union[str, None] = '88b53816f07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reactions', sa.Column('temperature_unit', sa.String(length=20), nullable=True))
    op.add_column('reactions', sa.Column('pressure_unit', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reactions', 'pressure_unit')
    op.drop_column('reactions', 'temperature_unit')
    # ### end Alembic commands ###
